//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC114_2115239_TranVanNam.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
    public partial class Post
    {
		[DisplayName("Mã Post")]
        public int PostId { get; set; }
		[DisplayName("Tiêu đề")]
		[StringLength(20, MinimumLength =5, ErrorMessage ="Tiêu đề phải trong khoảng từ 5 đến 20 ký tự")]

		public string Title { get; set; }
		[DisplayName("Nội dung")]
        public string Content { get; set; }
		[DisplayName("Mã Blog")]
        public int BlogId { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
